steps:
- name: gcr.io/kaniko-project/executor
  args:
  - --destination=gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA
  - --cache=true

- name: 'gcr.io/cloud-builders/docker'
  args: 
  - pull
  - gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA

- name: 'gcr.io/gcp-runtimes/container-structure-test'
  args: 
  - test 
  - --image
  - gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA
  - --config
  - container-structure-test.yml

- name: 'gcr.io/cloud-builders/docker'
  secretEnv:
  - DOCKERHUB_PASSWORD
  entrypoint: 'bash'
  args: 
  - '-c'
  - |
    if [ $BRANCH_NAME -eq "master" ]; then
      $VERSION="latest"
    else
      $VERSION=$BRANCH_NAME
    fi

    docker login --username=drecomdockerhub --password=$$DOCKERHUB_PASSWORD
    docker tag gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA drecom/centos-ruby:$VERSION
    docker push drecom/centos-ruby:$_BRANCH_NAME


secrets:
- kmsKeyName: projects/gcp-dre-dev/locations/global/keyRings/drecom-dockerhub/cryptoKeys/drecom-dockerhub
  secretEnv:
    DOCKERHUB_PASSWORD: CiQAVyjejT2cYeIb3kVx+go8Q54lyQN4s8XL2AEM1ngWycCOpkESSAAUNAqLElsfQ2pIe+Wabxs7DcF+4YIc0i+gRmOl/qxil2/DgRAEYSoZH33N8/yOQ0MpXOmpt0BZRfp8Ed+jJMUzLiRz7SLOqA==
